export const LOAD_ALL_PIZZAS = "LOAD_ALL_PIZZAS";
export const SHOW_ALL_PIZZAS = "SHOW_ALL_PIZZAS";
export const FILTER_PRODUCTS_TO_SHOW = "FILTER_PRODUCTS_TO_SHOW";


export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DECREMENT_AMOUNT = "DECREMENT_AMOUNT";
export const INCREMENT_AMOUNT = "INCREMENT_AMOUNT"; 
